project:
  type: website

website:
  title: "NAIF"
  site-url: "https://eth-library.github.io/naif/"
  repo-url: "https://github.com/eth-library/naif"
  issue-url: "https://github.com/eth-library/naif/issues/new/choose"
  repo-actions: [issue]
  favicon: favicon.svg

format:
  html:
    theme:
      light: [brand, cosmo, base_colors.scss, custom.scss]
    css: styles.css
    canonical-url: true
