exclude = [
  "https://www.gnu.org/licenses/",
  "https://www.gnu.org/licenses/agpl-3.0.html",
  "https://www.makeareadme.com/"
]

timeout = 10
max_retries = 2
format = "compact"
no_progress = true
cache = true
max_cache_age = "7d"
accept = ["100..=103", "200..=299", "429", "503", "521", "522", "524"]
