repos:
  - repo: local
    hooks:
      - id: prettier-check
        name: Prettier check
        entry: npm run check
        language: system
        stages: [pre-commit]
      - id: lychee-check
        name: Lychee link check
        entry: npm run lychee-check
        language: system
        stages: [pre-commit]
