project:
  type: website
  render:
    - "*.qmd"
    - "blog/index.qmd"
    - "posts/**/index.qmd"
    - "events/**/index.qmd"
    - "!blog/_template-*/**"

website:
  title: "NAIF"
  site-url: "https://eth-library.github.io/naif/"
  description:
    "National Approach for Interoperable repositories and Findable research results (NAIF):
    improving interoperability and metadata quality across Swiss institutional repositories."
  image: "/images/logos/all-logos.jpg"
  open-graph: true
  twitter-card: true
  navbar:
    left:
      - text: Home
        menu:
          - text: Blog
            href: blog/index.qmd
          - text: Events
            href: events/index.qmd
      - href: about.qmd
        text: About
      - href: https://zenodo.org/communities/naif
        text: Docs
    pinned: true
  page-footer:
    center:
      - text: "&copy; ETH Library &#x00B7; Powered by Quarto"
    right:
      - text: "Disclaimer"
        href: disclaimer.qmd

format:
  html:
    theme:
      light: [cosmo, base_colors.scss, custom.scss]
    css: styles.css
    canonical-url: true
    toc: true
    toc-expand: true
    toc-title: " "
    mainfont: Barlow
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    footnotes-hover: true
    anchor-sections: false
    include-after-body:
      - traffic.html
      - includes/get-involved.html
    email-obfuscation: references
